[workspace]
authors = ["ShanMehr <ishanmeher25@gmail.com>"]
channels = ["conda-forge"]
name = "research_paper_pipeline"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pull-secrets = "infisical export --path=\"/web-app\" --env=dev > .env"

[system-requirements]
cuda = "12.9"

[dependencies]
pytorch = ">=2.7.0,<3"
ipykernel = ">=6.29.5,<7"
langgraph = ">=0.4.5,<0.5"
ipywidgets = ">=8.1.7,<9"
langchain-huggingface = ">=0.2.0,<0.3"
sentence-transformers = ">=4.1.0,<5"
psycopg = ">=3.2.9,<4"
polars = ">=1.29.0,<2"
ray-data = ">=2.46.0,<3"
psycopg2 = ">=2.9.10,<3"

[pypi-dependencies]
langchain-postgres = ">=0.0.13, <0.0.14"
kagglehub = ">=0.3.12, <0.4"
dotenv = ">=0.9.9, <0.10"
ray = ">=2.46.0, <3"
dask = ">=2025.5.1, <2026"
polars = "*"
modin = ">=0.33.1, <0.34"
sqlalchemy = ">=2.0.41, <3"
